--- 
jobs: 
  build: 
    docker: 
      ? "-image"
      : "circleci/openjdk:8"
    steps: 
      ? "-checkout"
      : 
        path: $CIRCLE_PROJECT_REPONAME
      ? "-run"
      : 
        command: "mvn -DskipTests clean install"
        name: "maven build"
    working_directory: ~/DemoOnetoManyRelation
version: 2
         


