version: 2
jobs:
   build:
     working_directory: ~/build
     docker:
        - image: circleci/openjdk:8
     steps:
        - checkout
            
        - run: mvn clean install -DskipTests
             
        - setup_remote_docker:
            docker_layer_caching: true
        

        - run: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -f sandeepyadav02/DemoOnetoManyRelation/Dockerfile -t sandeepyadav02/springboot_example .
            docker login -u $DOCKER_USER -p $DOCKER_PASS         
            docker push sandeepyadav02/springboot_example:$TAG

