version: 2
jobs:
   build:
     working_directory: ~/build
     docker:
        - image: circleci/openjdk:8
     steps:
        - checkout
            
        - run: mvn clean install -DskipTests
             
             
         


