version: 2
jobs:
   build:
     working_directory: ~/build
     docker:
        - image: circleci/openjdk:8
     steps:
        - checkout
            
        - run: mvn clean install -DskipTests
             
        - setup_remote_docker:
            docker_layer_caching: true
        

        - run: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -f ./Dockerfile -t springboot_example:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS         
            docker push sandy0204/sandeep/springboot_example:$TAG

