version: 2
jobs:
   build:
     working_directory: ~/build
     docker:
        - image: circleci/openjdk:8
     steps:
        - checkout
            
        - run: 
            name: build project
            command: mvn clean install -DskipTests
                
             
        - setup_remote_docker:
            docker_layer_caching: true
        

        - run:
            name: build and push docker image
            command: |
                TAG=0.1.$CIRCLE_BUILD_NUM
                docker build -f ./Dockerfile -t sandy0204/springboot .
                docker login -u $DOCKER_USER -p $DOCKER_PASS 
                docker tag sandy0204/springboot sandy/springboot:latest       
                docker push sandy0204/springboot:latest

