version: 2
jobs:
   build:
     working_directory: ~/build
     docker:
        image: circleci/openjdk:8
     steps:
        - checkout:
            path: $CIRCLE_PROJECT_REPONAME
        - run:
             name: mavenBuild
             shell: /bin/bash
             command: mvn -DskipTests clean install
         


