version: 2
jobs:
   build:
     working_directory: ~/build
     docker:
        - image: circleci/openjdk:8
     steps:
        - checkout
            
        - run: 
            name: "build project"
            command: mvn clean install -DskipTests
                
             
        - setup_remote_docker:
            docker_layer_caching: true
        

        - run:
            name: "docker build"
            command: "docker build -t $CIRCLE_PROJECT_REPONAME ."
                
        - run:
            name: "Push to GCloud Image Registry" 
            command: |
              echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
              sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
              sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
              sudo /opt/google-cloud-sdk/bin/gcloud config set project ${GCLOUD_PROJECT_ID}
              sudo docker tag $CIRCLE_PROJECT_REPONAME gcr.io/${GCLOUD_PROJECT_ID}/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
              sudo /opt/google-cloud-sdk/bin/gcloud docker -- push gcr.io/${GCLOUD_PROJECT_ID}/$CIRCLE_PROJECT_REPONAME
  
